version: '3'

services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: host.docker.internal:5432
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - C:\Users\scher\Desktop\security\themes\custom:/opt/jboss/keycloak/themes/custom
      - C:\Users\scher\Desktop\security\configuration\disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
    ports:
      - 8090:8080